name: Keep Render Site Alive

on:
  schedule:
    # Har 14 minute pe chalega
    - cron: '*/14 * * * *'
  workflow_dispatch:  # Manual run ke liye

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping my website
        run: |
          echo "ðŸ•’ Pinging at $(date)"
          curl -s  https://animabing.onrender.com/
          echo "âœ… Ping successful!"
